### ISSUE TITLE
The value [true] for property [isVisualBuilderEnabled] is not allowed for integrationInstanceType [Enterprisex]

### ISSUE THREAD

**Issue by pavanaleti-elsevier** [oracle/terraform-provider-oci#1907]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/oci v5.3.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
### Affected Resource(s)

oci_integration_integration_instance

### Terraform Configuration Files

```hcl

resource "oci_integration_integration_instance" "int_integration_instance_gen3" {
  compartment_id            = var.compartment_id
  display_name              = var.display_name
  idcs_at                   = var.idcs_auth_token
  integration_instance_type = "ENTERPRISEX"
  is_byol                   = var.int_integration_is_byol
  message_packs             = var.int_integration_message_packs
  is_file_server_enabled    = var.int_file_server_enabled
  is_visual_builder_enabled = true
  state                     = "ACTIVE"
  freeform_tags             = local.common_freeform_tags
}
```

### Expected Behavior

Terraform should create a new integration instance with VBCS enabled like it is working for integrationInstanceType = ENTERPRISE (Gen 2). 
### Actual Behavior

Terraform is throwing error `Unable to create integration instance; the value [true] for property [isVisualBuilderEnabled] is not allowed for integrationInstanceType [Enterprisex]` 
Since the error says `Enterprisex`, this is specific to gen3 instance
### Steps to Reproduce

1. `terraform apply`

**Comment by pavanaleti-elsevier** [comment]
Seems like this is fixed. I checked this in the latest version.

**Comment by pavanaleti-elsevier** [comment]
Surprisingly this is still a bug. I get this error in provider v5.44.0. 
Can someone please take a look at this?

**Comment by ramkannan2003** [comment]
I am trying to spin up an OIC GEN3 instance, but I am encountering this error for both STANDARDX and ENTERPRISEX editions. I am using the latest version of the OCI provider, 6.14.0.

 Error: 400-InvalidParameter, Unable to create integration instance; the value [true] for property [isVisualBuilderEnabled] is not allowed for integrationInstanceType [Enterprisex].

**Comment by lincetto** [comment]
Still happen with provider v6.18.0

`│ Error: 400-InvalidParameter, Unable to create integration instance; the value [true] for property [isVisualBuilderEnabled] is not allowed for integrationInstanceType [Standardx].
│ Suggestion: Please update the parameter(s) in the Terraform config as per error message Unable to create integration instance; the value [true] for property [isVisualBuilderEnabled] is not allowed for integrationInstanceType [Standardx].
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/integration_integration_instance 
│ API Reference: https://docs.oracle.com/iaas/api/#/en/integration/20190131/IntegrationInstance/CreateIntegrationInstance 
│ Request Target: POST https://integration.eu-frankfurt-1.ocp.oraclecloud.com/20190131/integrationInstances 
│ Provider version: 6.18.0, released on 2024-11-13.  
│ Service: Integration Instance 
│ Operation Name: CreateIntegrationInstance `

The strange part is that after the instance has been created with is_visual_builder_enabled = false, if we set is_visual_builder_enabled = true the instance is updated and visual builder is enabled

**Comment by MarcGueury** [comment]
Still there with 6.21.0.

The same happens for is_file_server_enabled...

  is_file_server_enabled    = true
  is_visual_builder_enabled = true

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.
